resolver: lts-20.19
save-hackage-creds: false

flags:
  hakyll:
    previewServer: true
    watchServer: true
    checkExternal: true
    usePandoc: true
    buildWebsite: true

packages:
  - .
  - extra
  # Include git modules as subdirectories
  - hakyll
  - latex-svg/latex-svg-hakyll
  - latex-svg/latex-svg-image
  - latex-svg/latex-svg-pandoc

nix:
  packages:
    - zlib

build:
  haddock: false
  haddock-deps: false

extra-deps: []
