resolver: lts-16.21
save-hackage-creds: false
allow-newer: true

flags:
  hakyll:
    previewServer: true
    watchServer:   true
    checkExternal: true
    usePandoc:     true
    buildWebsite:  true

packages:
  - '.'
  - 'extra'
  # Include Hakyll as subdirectory
  - 'hakyll'

nix:
  enable: false
  packages:
    - zlib

build:
  haddock: true
  haddock-hyperlink-source: true
  haddock-deps: false

extra-deps:
# Hakyll Dependencies:
- 'commonmark-0.1.0.2'
- 'commonmark-extensions-0.2.0.1'
- 'commonmark-pandoc-0.2.0.1'
- 'hslua-1.1.2'
- 'jira-wiki-markup-1.3.2'
- 'pandoc-2.10.1'
- 'pandoc-types-1.21'
# Blog Dependencies
- 'latex-svg-hakyll-0.2'
- 'latex-svg-image-0.2'
- 'latex-svg-pandoc-0.2.1'
- 'containers-0.6.4.1'
- 'text-1.2.4.0'
# I don't know why Dependencies
- 'binary-0.8.8.0'
- 'Cabal-3.2.1.0'
- 'parsec-3.1.14.0'
