resolver: lts-14.27
packages:
  - .
  - extra

extra-deps:
  - hakyll-4.13.4.0
  - latex-svg-hakyll-0.2
  - latex-svg-image-0.2
  - latex-svg-pandoc-0.2.1
  - containers-0.6.0.1
  - text-1.2.3.1
