name: Install Tools & Dependencies

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      name: Install pnpm

    - uses: actions/setup-node@v5
      name: Install Node.js
      with:
        node-version: 22
        cache: "pnpm"

    - run: pnpm install
      name: Install dependencies
      shell: bash
