name: Install Tools & Dependencies

runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Restore node_modules
      uses: actions/cache@v4
      id: cache
      with:
        path: node_modules
        key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          npm-${{ runner.os }}-

    - name: Install node_modules
      run: npm ci
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash

    - name: Generate Astro Types
      run: npx astro sync
      shell: bash
