name: Build Astro, deploy to S3
# Trigger this on every push to main that would change astro files
on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/blog.yml"
      - ".eslintignore"
      - ".eslintrc.cjs"
      - "astro.config.mjs"
      - "package-lock.json"
      - "package.json"
      - "postcss.config.cjs"
      - "tsconfig.json"
      - "src/**"
      - "public/**"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Tools & Dependencies
        uses: ./.github/actions/install

      - name: Restore Astro Cache
        uses: actions/cache@v4
        with:
          path: dist
          key: blog-cache-astro

      - name: Build Astro
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to S3
        run: aws s3 sync --delete ./dist/ s3://${{ secrets.AWS_S3_BUCKET }}
      - name: Create CloudFront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }} --paths "/*"
